name: Deploy MERN Application

on:
  push:
    branches:
      - master
      

jobs:
  deploy:
    name: Deploy Frontend and Backend
    runs-on: ubuntu-latest
    environment: mera

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy MERN Application to Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/azureuser/Mern-E-Commerce

            git pull origin master

            echo "Deploying Backend..."

            cd backend

            npm install

            pm2 restart ecommerce-backend || pm2 start server.js --name ecommerce-backend

            echo "Backend deployed successfully"

            cd ../frontend

            echo "Installing Frontend dependencies..."

            npm install

            echo "Building Frontend..."

            npm run build

            echo "Frontend deployed successfully"

            sudo rm -rf /var/www/html/*

            sudo cp -r dist/* /var/www/html/
